package com.cztr.routinealarm

import java.time.DayOfWeek
import java.time.DayOfWeek.*

/**
 * Minute-genauer Trainingsplan Montag bis Samstag.
 *
 * Zeitregel:
 * - ein Satz = 1 Minute
 * - Pause zwischen Saetzen derselben Uebung = 1 Minute
 * - Wechsel zu einer anderen Uebung = 2 Minuten
 *
 * Alle Trainingsereignisse sind ANNOUNCEMENTs. Dadurch kann die TTS
 * den Trainingsfluss fuehren, ohne fuer jeden Satz einen blockierenden
 * Full-Screen-Alarm zu erzwingen.
 */
object TrainingSchedule {

    private fun cue(
        day: DayOfWeek,
        hour: Int,
        minute: Int,
        id: String,
        title: String,
        spokenText: String = title
    ) = RoutineEvent(
        id = id,
        daysOfWeek = setOf(day),
        hour = hour,
        minute = minute,
        title = title,
        spokenText = spokenText,
        category = EventCategory.TRAINING,
        mode = EventMode.ANNOUNCEMENT
    )

    val monday: List<RoutineEvent> = listOf(
        cue(MONDAY, 17, 30, "training_mon_pullup_set_1", "Klimmzüge Satz 1", "Training startet. Klimmzüge breit im Obergriff, Satz 1."),
        cue(MONDAY, 17, 31, "training_mon_pullup_pause_1", "Pause", "Eine Minute Pause."),
        cue(MONDAY, 17, 32, "training_mon_pullup_set_2", "Klimmzüge Satz 2", "Klimmzüge schulterbreit im Obergriff, Satz 2."),
        cue(MONDAY, 17, 33, "training_mon_pullup_pause_2", "Pause", "Eine Minute Pause."),
        cue(MONDAY, 17, 34, "training_mon_pullup_set_3", "Klimmzüge Satz 3", "Klimmzüge eng im Obergriff, Satz 3."),
        cue(MONDAY, 17, 35, "training_mon_pullup_pause_3", "Pause", "Eine Minute Pause."),
        cue(MONDAY, 17, 36, "training_mon_pullup_set_4", "Klimmzüge Satz 4", "Klimmzüge mit Handtuch im Neutralgriff, Satz 4."),
        cue(MONDAY, 17, 37, "training_mon_transition_pullup_to_lat", "Wechsel zu Latzug", "Wechsel zu Latzug. Zwei Minuten."),
        cue(MONDAY, 17, 39, "training_mon_lat_set_1", "Latzug Satz 1", "Latzug breit im Obergriff, Satz 1."),
        cue(MONDAY, 17, 40, "training_mon_lat_pause_1", "Pause", "Eine Minute Pause."),
        cue(MONDAY, 17, 41, "training_mon_lat_set_2", "Latzug Satz 2", "Latzug schulterbreit im Obergriff, Satz 2."),
        cue(MONDAY, 17, 42, "training_mon_lat_pause_2", "Pause", "Eine Minute Pause."),
        cue(MONDAY, 17, 43, "training_mon_lat_set_3", "Latzug Satz 3", "Latzug schulterbreit im Untergriff, Satz 3."),
        cue(MONDAY, 17, 44, "training_mon_transition_lat_to_dips", "Wechsel zu Dips", "Wechsel zu Dips. Zwei Minuten."),
        cue(MONDAY, 17, 46, "training_mon_dips_set_1", "Dips Satz 1", "Dips aufrecht für Trizeps, Satz 1."),
        cue(MONDAY, 17, 47, "training_mon_dips_pause_1", "Pause", "Eine Minute Pause."),
        cue(MONDAY, 17, 48, "training_mon_dips_set_2", "Dips Satz 2", "Dips leicht vorgebeugt, Satz 2."),
        cue(MONDAY, 17, 49, "training_mon_dips_pause_2", "Pause", "Eine Minute Pause."),
        cue(MONDAY, 17, 50, "training_mon_dips_set_3", "Dips Satz 3", "Dips aufrecht für Trizeps, Satz 3."),
        cue(MONDAY, 17, 51, "training_mon_dips_pause_3", "Pause", "Eine Minute Pause."),
        cue(MONDAY, 17, 52, "training_mon_dips_set_4", "Dips Satz 4", "Dips leicht vorgebeugt, Satz 4."),
        cue(MONDAY, 17, 53, "training_mon_transition_dips_to_butterfly", "Wechsel zu Butterfly", "Wechsel zu Butterfly. Zwei Minuten."),
        cue(MONDAY, 17, 55, "training_mon_butterfly_set_1", "Butterfly Satz 1", "Butterfly, Satz 1."),
        cue(MONDAY, 17, 56, "training_mon_butterfly_pause_1", "Pause", "Eine Minute Pause."),
        cue(MONDAY, 17, 57, "training_mon_butterfly_set_2", "Butterfly Satz 2", "Butterfly, Satz 2."),
        cue(MONDAY, 17, 58, "training_mon_butterfly_pause_2", "Pause", "Eine Minute Pause."),
        cue(MONDAY, 17, 59, "training_mon_butterfly_set_3", "Butterfly Satz 3", "Butterfly, Satz 3."),
        cue(MONDAY, 18, 0, "training_mon_transition_butterfly_to_pushup", "Wechsel zu Liegestützbrett", "Wechsel zu Liegestützbrett. Zwei Minuten."),
        cue(MONDAY, 18, 2, "training_mon_pushup_set_1", "Liegestützbrett Satz 1", "Liegestützbrett Nummer eins, blau, Satz 1."),
        cue(MONDAY, 18, 3, "training_mon_pushup_pause_1", "Pause", "Eine Minute Pause."),
        cue(MONDAY, 18, 4, "training_mon_pushup_set_2", "Liegestützbrett Satz 2", "Liegestützbrett Nummer zwei, blau, Satz 2."),
        cue(MONDAY, 18, 5, "training_mon_pushup_pause_2", "Pause", "Eine Minute Pause."),
        cue(MONDAY, 18, 6, "training_mon_pushup_set_3", "Liegestützbrett Satz 3", "Liegestützbrett Nummer drei, blau, Satz 3."),
        cue(MONDAY, 18, 7, "training_mon_transition_pushup_to_squat", "Wechsel zu Kniebeugen", "Wechsel zu Kniebeugen. Zwei Minuten."),
        cue(MONDAY, 18, 9, "training_mon_squat_set_1", "Kniebeugen Satz 1", "Kniebeugen, Satz 1."),
        cue(MONDAY, 18, 10, "training_mon_squat_pause_1", "Pause", "Eine Minute Pause."),
        cue(MONDAY, 18, 11, "training_mon_squat_set_2", "Kniebeugen Satz 2", "Kniebeugen, Satz 2."),
        cue(MONDAY, 18, 12, "training_mon_squat_pause_2", "Pause", "Eine Minute Pause."),
        cue(MONDAY, 18, 13, "training_mon_squat_set_3", "Kniebeugen Satz 3", "Kniebeugen, Satz 3."),
        cue(MONDAY, 18, 14, "training_mon_squat_pause_3", "Pause", "Eine Minute Pause."),
        cue(MONDAY, 18, 15, "training_mon_squat_set_4", "Kniebeugen Satz 4", "Kniebeugen, Satz 4."),
        cue(MONDAY, 18, 16, "training_mon_transition_squat_to_hkr", "Wechsel zu Hanging Knee Raises", "Wechsel zu Hanging Knee Raises. Zwei Minuten."),
        cue(MONDAY, 18, 18, "training_mon_hkr_set_1", "Hanging Knee Raises Satz 1", "Hanging Knee Raises, Satz 1."),
        cue(MONDAY, 18, 19, "training_mon_hkr_pause_1", "Pause", "Eine Minute Pause."),
        cue(MONDAY, 18, 20, "training_mon_hkr_set_2", "Hanging Knee Raises Satz 2", "Hanging Knee Raises, Satz 2."),
        cue(MONDAY, 18, 21, "training_mon_hkr_pause_2", "Pause", "Eine Minute Pause."),
        cue(MONDAY, 18, 22, "training_mon_hkr_set_3", "Hanging Knee Raises Satz 3", "Hanging Knee Raises, Satz 3."),
        cue(MONDAY, 18, 23, "training_mon_transition_hkr_to_plank", "Wechsel zu Plank", "Wechsel zu Plank. Zwei Minuten."),
        cue(MONDAY, 18, 25, "training_mon_plank_set_1", "Plank Satz 1", "Plank, Satz 1."),
        cue(MONDAY, 18, 26, "training_mon_plank_pause_1", "Pause", "Eine Minute Pause."),
        cue(MONDAY, 18, 27, "training_mon_plank_set_2", "Plank Satz 2", "Plank, Satz 2."),
        cue(MONDAY, 18, 28, "training_mon_plank_pause_2", "Pause", "Eine Minute Pause."),
        cue(MONDAY, 18, 29, "training_mon_plank_set_3", "Plank Satz 3", "Plank, Satz 3."),
        cue(MONDAY, 18, 30, "training_mon_done_shower", "Training beendet – duschen", "Training beendet. Jetzt zehn Minuten duschen."),
        cue(MONDAY, 18, 40, "training_mon_dry_dress", "Abtrocknen und anziehen", "Dusche beendet. Jetzt abtrocknen und anziehen. Bis 18:45.")
    )

    val tuesday: List<RoutineEvent> = listOf(
        cue(TUESDAY, 17, 30, "training_tue_squat_set_1", "Kniebeugen Satz 1", "Training startet. Kniebeugen, Satz 1."),
        cue(TUESDAY, 17, 31, "training_tue_squat_pause_1", "Pause", "Eine Minute Pause."),
        cue(TUESDAY, 17, 32, "training_tue_squat_set_2", "Kniebeugen Satz 2", "Kniebeugen, Satz 2."),
        cue(TUESDAY, 17, 33, "training_tue_squat_pause_2", "Pause", "Eine Minute Pause."),
        cue(TUESDAY, 17, 34, "training_tue_squat_set_3", "Kniebeugen Satz 3", "Kniebeugen, Satz 3."),
        cue(TUESDAY, 17, 35, "training_tue_squat_pause_3", "Pause", "Eine Minute Pause."),
        cue(TUESDAY, 17, 36, "training_tue_squat_set_4", "Kniebeugen Satz 4", "Kniebeugen, Satz 4."),
        cue(TUESDAY, 17, 37, "training_tue_transition_squat_to_leg_extension", "Wechsel zu Beinstrecker", "Wechsel zu Beinstrecker. Zwei Minuten."),
        cue(TUESDAY, 17, 39, "training_tue_leg_extension_set_1", "Beinstrecker Satz 1", "Beinstrecker, Satz 1."),
        cue(TUESDAY, 17, 40, "training_tue_leg_extension_pause_1", "Pause", "Eine Minute Pause."),
        cue(TUESDAY, 17, 41, "training_tue_leg_extension_set_2", "Beinstrecker Satz 2", "Beinstrecker, Satz 2."),
        cue(TUESDAY, 17, 42, "training_tue_leg_extension_pause_2", "Pause", "Eine Minute Pause."),
        cue(TUESDAY, 17, 43, "training_tue_leg_extension_set_3", "Beinstrecker Satz 3", "Beinstrecker, Satz 3."),
        cue(TUESDAY, 17, 44, "training_tue_leg_extension_pause_3", "Pause", "Eine Minute Pause."),
        cue(TUESDAY, 17, 45, "training_tue_leg_extension_set_4", "Beinstrecker Satz 4", "Beinstrecker, Satz 4."),
        cue(TUESDAY, 17, 46, "training_tue_transition_leg_extension_to_lunges", "Wechsel zu Ausfallschritte", "Wechsel zu Ausfallschritte. Zwei Minuten."),
        cue(TUESDAY, 17, 48, "training_tue_lunges_set_1", "Ausfallschritte Satz 1", "Ausfallschritte, Satz 1."),
        cue(TUESDAY, 17, 49, "training_tue_lunges_pause_1", "Pause", "Eine Minute Pause."),
        cue(TUESDAY, 17, 50, "training_tue_lunges_set_2", "Ausfallschritte Satz 2", "Ausfallschritte, Satz 2."),
        cue(TUESDAY, 17, 51, "training_tue_lunges_pause_2", "Pause", "Eine Minute Pause."),
        cue(TUESDAY, 17, 52, "training_tue_lunges_set_3", "Ausfallschritte Satz 3", "Ausfallschritte, Satz 3."),
        cue(TUESDAY, 17, 53, "training_tue_lunges_pause_3", "Pause", "Eine Minute Pause."),
        cue(TUESDAY, 17, 54, "training_tue_lunges_set_4", "Ausfallschritte Satz 4", "Ausfallschritte, Satz 4."),
        cue(TUESDAY, 17, 55, "training_tue_transition_lunges_to_calves", "Wechsel zu Wadenheben", "Wechsel zu Wadenheben. Zwei Minuten."),
        cue(TUESDAY, 17, 57, "training_tue_calves_set_1", "Wadenheben Satz 1", "Wadenheben, Satz 1."),
        cue(TUESDAY, 17, 58, "training_tue_calves_pause_1", "Pause", "Eine Minute Pause."),
        cue(TUESDAY, 17, 59, "training_tue_calves_set_2", "Wadenheben Satz 2", "Wadenheben, Satz 2."),
        cue(TUESDAY, 18, 0, "training_tue_calves_pause_2", "Pause", "Eine Minute Pause."),
        cue(TUESDAY, 18, 1, "training_tue_calves_set_3", "Wadenheben Satz 3", "Wadenheben, Satz 3."),
        cue(TUESDAY, 18, 2, "training_tue_calves_pause_3", "Pause", "Eine Minute Pause."),
        cue(TUESDAY, 18, 3, "training_tue_calves_set_4", "Wadenheben Satz 4", "Wadenheben, Satz 4."),
        cue(TUESDAY, 18, 4, "training_tue_transition_calves_to_jump_squat", "Wechsel zu Sprungkniebeugen", "Wechsel zu Sprungkniebeugen. Zwei Minuten."),
        cue(TUESDAY, 18, 6, "training_tue_jump_squat_set_1", "Sprungkniebeugen Satz 1", "Sprungkniebeugen, Satz 1."),
        cue(TUESDAY, 18, 7, "training_tue_jump_squat_pause_1", "Pause", "Eine Minute Pause."),
        cue(TUESDAY, 18, 8, "training_tue_jump_squat_set_2", "Sprungkniebeugen Satz 2", "Sprungkniebeugen, Satz 2."),
        cue(TUESDAY, 18, 9, "training_tue_jump_squat_pause_2", "Pause", "Eine Minute Pause."),
        cue(TUESDAY, 18, 10, "training_tue_jump_squat_set_3", "Sprungkniebeugen Satz 3", "Sprungkniebeugen, Satz 3."),
        cue(TUESDAY, 18, 11, "training_tue_transition_jump_squat_to_hkr", "Wechsel zu Hanging Knee Raises", "Wechsel zu Hanging Knee Raises. Zwei Minuten."),
        cue(TUESDAY, 18, 13, "training_tue_hkr_set_1", "Hanging Knee Raises Satz 1", "Hanging Knee Raises, Satz 1."),
        cue(TUESDAY, 18, 14, "training_tue_hkr_pause_1", "Pause", "Eine Minute Pause."),
        cue(TUESDAY, 18, 15, "training_tue_hkr_set_2", "Hanging Knee Raises Satz 2", "Hanging Knee Raises, Satz 2."),
        cue(TUESDAY, 18, 16, "training_tue_hkr_pause_2", "Pause", "Eine Minute Pause."),
        cue(TUESDAY, 18, 17, "training_tue_hkr_set_3", "Hanging Knee Raises Satz 3", "Hanging Knee Raises, Satz 3."),
        cue(TUESDAY, 18, 18, "training_tue_transition_hkr_to_side_plank", "Wechsel zu Side Plank", "Wechsel zu Side Plank. Zwei Minuten."),
        cue(TUESDAY, 18, 20, "training_tue_side_plank_set_1", "Side Plank Satz 1", "Side Plank, Satz 1."),
        cue(TUESDAY, 18, 21, "training_tue_side_plank_pause_1", "Pause", "Eine Minute Pause."),
        cue(TUESDAY, 18, 22, "training_tue_side_plank_set_2", "Side Plank Satz 2", "Side Plank, Satz 2."),
        cue(TUESDAY, 18, 23, "training_tue_side_plank_pause_2", "Pause", "Eine Minute Pause."),
        cue(TUESDAY, 18, 24, "training_tue_side_plank_set_3", "Side Plank Satz 3", "Side Plank, Satz 3."),
        cue(TUESDAY, 18, 25, "training_tue_done_shower", "Training beendet – duschen", "Training beendet. Jetzt zehn Minuten duschen."),
        cue(TUESDAY, 18, 35, "training_tue_dry_dress", "Abtrocknen und anziehen", "Dusche beendet. Jetzt abtrocknen und anziehen. Bis 18:40.")
    )

    val wednesday: List<RoutineEvent> = listOf(
        cue(WEDNESDAY, 17, 30, "training_wed_squat_set_1", "Kniebeugen Satz 1", "Training startet. Kniebeugen, Satz 1."),
        cue(WEDNESDAY, 17, 31, "training_wed_squat_pause_1", "Pause", "Eine Minute Pause."),
        cue(WEDNESDAY, 17, 32, "training_wed_squat_set_2", "Kniebeugen Satz 2", "Kniebeugen, Satz 2."),
        cue(WEDNESDAY, 17, 33, "training_wed_squat_pause_2", "Pause", "Eine Minute Pause."),
        cue(WEDNESDAY, 17, 34, "training_wed_squat_set_3", "Kniebeugen Satz 3", "Kniebeugen, Satz 3."),
        cue(WEDNESDAY, 17, 35, "training_wed_squat_pause_3", "Pause", "Eine Minute Pause."),
        cue(WEDNESDAY, 17, 36, "training_wed_squat_set_4", "Kniebeugen Satz 4", "Kniebeugen, Satz 4."),
        cue(WEDNESDAY, 17, 37, "training_wed_transition_squat_to_pullup", "Wechsel zu Klimmzüge", "Wechsel zu Klimmzüge. Zwei Minuten."),
        cue(WEDNESDAY, 17, 39, "training_wed_pullup_set_1", "Klimmzüge Satz 1", "Klimmzüge schulterbreit im Untergriff, Satz 1."),
        cue(WEDNESDAY, 17, 40, "training_wed_pullup_pause_1", "Pause", "Eine Minute Pause."),
        cue(WEDNESDAY, 17, 41, "training_wed_pullup_set_2", "Klimmzüge Satz 2", "Klimmzüge eng im Untergriff, Satz 2."),
        cue(WEDNESDAY, 17, 42, "training_wed_pullup_pause_2", "Pause", "Eine Minute Pause."),
        cue(WEDNESDAY, 17, 43, "training_wed_pullup_set_3", "Klimmzüge Satz 3", "Klimmzüge schulterbreit im Obergriff, Satz 3."),
        cue(WEDNESDAY, 17, 44, "training_wed_pullup_pause_3", "Pause", "Eine Minute Pause."),
        cue(WEDNESDAY, 17, 45, "training_wed_pullup_set_4", "Klimmzüge Satz 4", "Klimmzüge mit Handtuch im Neutralgriff, Satz 4."),
        cue(WEDNESDAY, 17, 46, "training_wed_transition_pullup_to_lat", "Wechsel zu Latzug", "Wechsel zu Latzug. Zwei Minuten."),
        cue(WEDNESDAY, 17, 48, "training_wed_lat_set_1", "Latzug Satz 1", "Latzug eng im Obergriff, Satz 1."),
        cue(WEDNESDAY, 17, 49, "training_wed_lat_pause_1", "Pause", "Eine Minute Pause."),
        cue(WEDNESDAY, 17, 50, "training_wed_lat_set_2", "Latzug Satz 2", "Latzug eng im Untergriff, Satz 2."),
        cue(WEDNESDAY, 17, 51, "training_wed_lat_pause_2", "Pause", "Eine Minute Pause."),
        cue(WEDNESDAY, 17, 52, "training_wed_lat_set_3", "Latzug Satz 3", "Latzug schulterbreit im Obergriff, Satz 3."),
        cue(WEDNESDAY, 17, 53, "training_wed_transition_lat_to_dips", "Wechsel zu Dips", "Wechsel zu Dips. Zwei Minuten."),
        cue(WEDNESDAY, 17, 55, "training_wed_dips_set_1", "Dips Satz 1", "Dips aufrecht für Trizeps, Satz 1."),
        cue(WEDNESDAY, 17, 56, "training_wed_dips_pause_1", "Pause", "Eine Minute Pause."),
        cue(WEDNESDAY, 17, 57, "training_wed_dips_set_2", "Dips Satz 2", "Dips leicht vorgebeugt, Satz 2."),
        cue(WEDNESDAY, 17, 58, "training_wed_dips_pause_2", "Pause", "Eine Minute Pause."),
        cue(WEDNESDAY, 17, 59, "training_wed_dips_set_3", "Dips Satz 3", "Dips aufrecht für Trizeps, Satz 3."),
        cue(WEDNESDAY, 18, 0, "training_wed_dips_pause_3", "Pause", "Eine Minute Pause."),
        cue(WEDNESDAY, 18, 1, "training_wed_dips_set_4", "Dips Satz 4", "Dips leicht vorgebeugt, Satz 4."),
        cue(WEDNESDAY, 18, 2, "training_wed_transition_dips_to_row", "Wechsel zu Rudern", "Wechsel zu Rudern. Zwei Minuten."),
        cue(WEDNESDAY, 18, 4, "training_wed_row_set_1", "Rudern Satz 1", "Rudern breit im Obergriff, Satz 1."),
        cue(WEDNESDAY, 18, 5, "training_wed_row_pause_1", "Pause", "Eine Minute Pause."),
        cue(WEDNESDAY, 18, 6, "training_wed_row_set_2", "Rudern Satz 2", "Rudern schulterbreit im Untergriff, Satz 2."),
        cue(WEDNESDAY, 18, 7, "training_wed_row_pause_2", "Pause", "Eine Minute Pause."),
        cue(WEDNESDAY, 18, 8, "training_wed_row_set_3", "Rudern Satz 3", "Rudern eng im Obergriff, Satz 3."),
        cue(WEDNESDAY, 18, 9, "training_wed_transition_row_to_pushup", "Wechsel zu Liegestützbrett", "Wechsel zu Liegestützbrett. Zwei Minuten."),
        cue(WEDNESDAY, 18, 11, "training_wed_pushup_set_1", "Liegestützbrett Satz 1", "Liegestützbrett Nummer vier, rot, Satz 1."),
        cue(WEDNESDAY, 18, 12, "training_wed_pushup_pause_1", "Pause", "Eine Minute Pause."),
        cue(WEDNESDAY, 18, 13, "training_wed_pushup_set_2", "Liegestützbrett Satz 2", "Liegestützbrett Nummer fünf, rot, Satz 2."),
        cue(WEDNESDAY, 18, 14, "training_wed_pushup_pause_2", "Pause", "Eine Minute Pause."),
        cue(WEDNESDAY, 18, 15, "training_wed_pushup_set_3", "Liegestützbrett Satz 3", "Liegestützbrett Nummer sechs, gelb, Satz 3."),
        cue(WEDNESDAY, 18, 16, "training_wed_transition_pushup_to_lsit", "Wechsel zu L-Sit", "Wechsel zu L-Sit. Zwei Minuten."),
        cue(WEDNESDAY, 18, 18, "training_wed_lsit_set_1", "L-Sit Satz 1", "L-Sit, Satz 1."),
        cue(WEDNESDAY, 18, 19, "training_wed_lsit_pause_1", "Pause", "Eine Minute Pause."),
        cue(WEDNESDAY, 18, 20, "training_wed_lsit_set_2", "L-Sit Satz 2", "L-Sit, Satz 2."),
        cue(WEDNESDAY, 18, 21, "training_wed_lsit_pause_2", "Pause", "Eine Minute Pause."),
        cue(WEDNESDAY, 18, 22, "training_wed_lsit_set_3", "L-Sit Satz 3", "L-Sit, Satz 3."),
        cue(WEDNESDAY, 18, 23, "training_wed_transition_lsit_to_plank", "Wechsel zu Plank", "Wechsel zu Plank. Zwei Minuten."),
        cue(WEDNESDAY, 18, 25, "training_wed_plank_set_1", "Plank Satz 1", "Plank, Satz 1."),
        cue(WEDNESDAY, 18, 26, "training_wed_plank_pause_1", "Pause", "Eine Minute Pause."),
        cue(WEDNESDAY, 18, 27, "training_wed_plank_set_2", "Plank Satz 2", "Plank, Satz 2."),
        cue(WEDNESDAY, 18, 28, "training_wed_plank_pause_2", "Pause", "Eine Minute Pause."),
        cue(WEDNESDAY, 18, 29, "training_wed_plank_set_3", "Plank Satz 3", "Plank, Satz 3."),
        cue(WEDNESDAY, 18, 30, "training_wed_done_shower", "Training beendet – duschen", "Training beendet. Jetzt zehn Minuten duschen."),
        cue(WEDNESDAY, 18, 40, "training_wed_dry_dress", "Abtrocknen und anziehen", "Dusche beendet. Jetzt abtrocknen und anziehen. Bis 18:45.")
    )

    val thursday: List<RoutineEvent> = listOf(
        cue(THURSDAY, 17, 30, "training_thu_squat_set_1", "Kniebeugen Satz 1", "Training startet. Kniebeugen, Satz 1."),
        cue(THURSDAY, 17, 31, "training_thu_squat_pause_1", "Pause", "Eine Minute Pause."),
        cue(THURSDAY, 17, 32, "training_thu_squat_set_2", "Kniebeugen Satz 2", "Kniebeugen, Satz 2."),
        cue(THURSDAY, 17, 33, "training_thu_squat_pause_2", "Pause", "Eine Minute Pause."),
        cue(THURSDAY, 17, 34, "training_thu_squat_set_3", "Kniebeugen Satz 3", "Kniebeugen, Satz 3."),
        cue(THURSDAY, 17, 35, "training_thu_squat_pause_3", "Pause", "Eine Minute Pause."),
        cue(THURSDAY, 17, 36, "training_thu_squat_set_4", "Kniebeugen Satz 4", "Kniebeugen, Satz 4."),
        cue(THURSDAY, 17, 37, "training_thu_transition_squat_to_lunges", "Wechsel zu Ausfallschritte", "Wechsel zu Ausfallschritte. Zwei Minuten."),
        cue(THURSDAY, 17, 39, "training_thu_lunges_set_1", "Ausfallschritte Satz 1", "Ausfallschritte, Satz 1."),
        cue(THURSDAY, 17, 40, "training_thu_lunges_pause_1", "Pause", "Eine Minute Pause."),
        cue(THURSDAY, 17, 41, "training_thu_lunges_set_2", "Ausfallschritte Satz 2", "Ausfallschritte, Satz 2."),
        cue(THURSDAY, 17, 42, "training_thu_lunges_pause_2", "Pause", "Eine Minute Pause."),
        cue(THURSDAY, 17, 43, "training_thu_lunges_set_3", "Ausfallschritte Satz 3", "Ausfallschritte, Satz 3."),
        cue(THURSDAY, 17, 44, "training_thu_lunges_pause_3", "Pause", "Eine Minute Pause."),
        cue(THURSDAY, 17, 45, "training_thu_lunges_set_4", "Ausfallschritte Satz 4", "Ausfallschritte, Satz 4."),
        cue(THURSDAY, 17, 46, "training_thu_transition_lunges_to_calves", "Wechsel zu Wadenheben", "Wechsel zu Wadenheben. Zwei Minuten."),
        cue(THURSDAY, 17, 48, "training_thu_calves_set_1", "Wadenheben Satz 1", "Wadenheben, Satz 1."),
        cue(THURSDAY, 17, 49, "training_thu_calves_pause_1", "Pause", "Eine Minute Pause."),
        cue(THURSDAY, 17, 50, "training_thu_calves_set_2", "Wadenheben Satz 2", "Wadenheben, Satz 2."),
        cue(THURSDAY, 17, 51, "training_thu_calves_pause_2", "Pause", "Eine Minute Pause."),
        cue(THURSDAY, 17, 52, "training_thu_calves_set_3", "Wadenheben Satz 3", "Wadenheben, Satz 3."),
        cue(THURSDAY, 17, 53, "training_thu_calves_pause_3", "Pause", "Eine Minute Pause."),
        cue(THURSDAY, 17, 54, "training_thu_calves_set_4", "Wadenheben Satz 4", "Wadenheben, Satz 4."),
        cue(THURSDAY, 17, 55, "training_thu_transition_calves_to_jump_squat", "Wechsel zu Sprungkniebeugen", "Wechsel zu Sprungkniebeugen. Zwei Minuten."),
        cue(THURSDAY, 17, 57, "training_thu_jump_squat_set_1", "Sprungkniebeugen Satz 1", "Sprungkniebeugen, Satz 1."),
        cue(THURSDAY, 17, 58, "training_thu_jump_squat_pause_1", "Pause", "Eine Minute Pause."),
        cue(THURSDAY, 17, 59, "training_thu_jump_squat_set_2", "Sprungkniebeugen Satz 2", "Sprungkniebeugen, Satz 2."),
        cue(THURSDAY, 18, 0, "training_thu_jump_squat_pause_2", "Pause", "Eine Minute Pause."),
        cue(THURSDAY, 18, 1, "training_thu_jump_squat_set_3", "Sprungkniebeugen Satz 3", "Sprungkniebeugen, Satz 3."),
        cue(THURSDAY, 18, 2, "training_thu_transition_jump_squat_to_leg_extension_light", "Wechsel zu leichter Beinstrecker", "Wechsel zu leichter Beinstrecker. Zwei Minuten."),
        cue(THURSDAY, 18, 4, "training_thu_leg_extension_light_set_1", "leichter Beinstrecker Satz 1", "Leichter Beinstrecker, Satz 1."),
        cue(THURSDAY, 18, 5, "training_thu_leg_extension_light_pause_1", "Pause", "Eine Minute Pause."),
        cue(THURSDAY, 18, 6, "training_thu_leg_extension_light_set_2", "leichter Beinstrecker Satz 2", "Leichter Beinstrecker, Satz 2."),
        cue(THURSDAY, 18, 7, "training_thu_leg_extension_light_pause_2", "Pause", "Eine Minute Pause."),
        cue(THURSDAY, 18, 8, "training_thu_leg_extension_light_set_3", "leichter Beinstrecker Satz 3", "Leichter Beinstrecker, Satz 3."),
        cue(THURSDAY, 18, 9, "training_thu_transition_leg_extension_light_to_hkr", "Wechsel zu Hanging Knee Raises", "Wechsel zu Hanging Knee Raises. Zwei Minuten."),
        cue(THURSDAY, 18, 11, "training_thu_hkr_set_1", "Hanging Knee Raises Satz 1", "Hanging Knee Raises, Satz 1."),
        cue(THURSDAY, 18, 12, "training_thu_hkr_pause_1", "Pause", "Eine Minute Pause."),
        cue(THURSDAY, 18, 13, "training_thu_hkr_set_2", "Hanging Knee Raises Satz 2", "Hanging Knee Raises, Satz 2."),
        cue(THURSDAY, 18, 14, "training_thu_hkr_pause_2", "Pause", "Eine Minute Pause."),
        cue(THURSDAY, 18, 15, "training_thu_hkr_set_3", "Hanging Knee Raises Satz 3", "Hanging Knee Raises, Satz 3."),
        cue(THURSDAY, 18, 16, "training_thu_hkr_pause_3", "Pause", "Eine Minute Pause."),
        cue(THURSDAY, 18, 17, "training_thu_hkr_set_4", "Hanging Knee Raises Satz 4", "Hanging Knee Raises, Satz 4."),
        cue(THURSDAY, 18, 18, "training_thu_transition_hkr_to_side_plank", "Wechsel zu Side Plank", "Wechsel zu Side Plank. Zwei Minuten."),
        cue(THURSDAY, 18, 20, "training_thu_side_plank_set_1", "Side Plank Satz 1", "Side Plank, Satz 1."),
        cue(THURSDAY, 18, 21, "training_thu_side_plank_pause_1", "Pause", "Eine Minute Pause."),
        cue(THURSDAY, 18, 22, "training_thu_side_plank_set_2", "Side Plank Satz 2", "Side Plank, Satz 2."),
        cue(THURSDAY, 18, 23, "training_thu_side_plank_pause_2", "Pause", "Eine Minute Pause."),
        cue(THURSDAY, 18, 24, "training_thu_side_plank_set_3", "Side Plank Satz 3", "Side Plank, Satz 3."),
        cue(THURSDAY, 18, 25, "training_thu_done_shower", "Training beendet – duschen", "Training beendet. Jetzt zehn Minuten duschen."),
        cue(THURSDAY, 18, 35, "training_thu_dry_dress", "Abtrocknen und anziehen", "Dusche beendet. Jetzt abtrocknen und anziehen. Bis 18:40.")
    )

    val friday: List<RoutineEvent> = listOf(
        cue(FRIDAY, 17, 30, "training_fri_pullup_set_1", "Klimmzüge Satz 1", "Training startet. Klimmzüge breit im Obergriff, Satz 1."),
        cue(FRIDAY, 17, 31, "training_fri_pullup_pause_1", "Pause", "Eine Minute Pause."),
        cue(FRIDAY, 17, 32, "training_fri_pullup_set_2", "Klimmzüge Satz 2", "Klimmzüge schulterbreit im Untergriff, Satz 2."),
        cue(FRIDAY, 17, 33, "training_fri_pullup_pause_2", "Pause", "Eine Minute Pause."),
        cue(FRIDAY, 17, 34, "training_fri_pullup_set_3", "Klimmzüge Satz 3", "Klimmzüge eng im Obergriff, Satz 3."),
        cue(FRIDAY, 17, 35, "training_fri_pullup_pause_3", "Pause", "Eine Minute Pause."),
        cue(FRIDAY, 17, 36, "training_fri_pullup_set_4", "Klimmzüge Satz 4", "Klimmzüge eng im Untergriff, Satz 4."),
        cue(FRIDAY, 17, 37, "training_fri_transition_pullup_to_lat", "Wechsel zu Latzug", "Wechsel zu Latzug. Zwei Minuten."),
        cue(FRIDAY, 17, 39, "training_fri_lat_set_1", "Latzug Satz 1", "Latzug breit im Obergriff, Satz 1."),
        cue(FRIDAY, 17, 40, "training_fri_lat_pause_1", "Pause", "Eine Minute Pause."),
        cue(FRIDAY, 17, 41, "training_fri_lat_set_2", "Latzug Satz 2", "Latzug schulterbreit im Untergriff, Satz 2."),
        cue(FRIDAY, 17, 42, "training_fri_lat_pause_2", "Pause", "Eine Minute Pause."),
        cue(FRIDAY, 17, 43, "training_fri_lat_set_3", "Latzug Satz 3", "Latzug eng im Obergriff, Satz 3."),
        cue(FRIDAY, 17, 44, "training_fri_transition_lat_to_dips", "Wechsel zu Dips", "Wechsel zu Dips. Zwei Minuten."),
        cue(FRIDAY, 17, 46, "training_fri_dips_set_1", "Dips Satz 1", "Dips aufrecht für Trizeps, Satz 1."),
        cue(FRIDAY, 17, 47, "training_fri_dips_pause_1", "Pause", "Eine Minute Pause."),
        cue(FRIDAY, 17, 48, "training_fri_dips_set_2", "Dips Satz 2", "Dips leicht vorgebeugt, Satz 2."),
        cue(FRIDAY, 17, 49, "training_fri_dips_pause_2", "Pause", "Eine Minute Pause."),
        cue(FRIDAY, 17, 50, "training_fri_dips_set_3", "Dips Satz 3", "Dips aufrecht für Trizeps, Satz 3."),
        cue(FRIDAY, 17, 51, "training_fri_dips_pause_3", "Pause", "Eine Minute Pause."),
        cue(FRIDAY, 17, 52, "training_fri_dips_set_4", "Dips Satz 4", "Dips leicht vorgebeugt, Satz 4."),
        cue(FRIDAY, 17, 53, "training_fri_transition_dips_to_butterfly", "Wechsel zu Butterfly", "Wechsel zu Butterfly. Zwei Minuten."),
        cue(FRIDAY, 17, 55, "training_fri_butterfly_set_1", "Butterfly Satz 1", "Butterfly, Satz 1."),
        cue(FRIDAY, 17, 56, "training_fri_butterfly_pause_1", "Pause", "Eine Minute Pause."),
        cue(FRIDAY, 17, 57, "training_fri_butterfly_set_2", "Butterfly Satz 2", "Butterfly, Satz 2."),
        cue(FRIDAY, 17, 58, "training_fri_butterfly_pause_2", "Pause", "Eine Minute Pause."),
        cue(FRIDAY, 17, 59, "training_fri_butterfly_set_3", "Butterfly Satz 3", "Butterfly, Satz 3."),
        cue(FRIDAY, 18, 0, "training_fri_butterfly_pause_3", "Pause", "Eine Minute Pause."),
        cue(FRIDAY, 18, 1, "training_fri_butterfly_set_4", "Butterfly Satz 4", "Butterfly, Satz 4."),
        cue(FRIDAY, 18, 2, "training_fri_transition_butterfly_to_pushup", "Wechsel zu Liegestützbrett", "Wechsel zu Liegestützbrett. Zwei Minuten."),
        cue(FRIDAY, 18, 4, "training_fri_pushup_set_1", "Liegestützbrett Satz 1", "Liegestützbrett Nummer sieben, gelb, Satz 1."),
        cue(FRIDAY, 18, 5, "training_fri_pushup_pause_1", "Pause", "Eine Minute Pause."),
        cue(FRIDAY, 18, 6, "training_fri_pushup_set_2", "Liegestützbrett Satz 2", "Liegestützbrett Nummer acht, grün, Satz 2."),
        cue(FRIDAY, 18, 7, "training_fri_pushup_pause_2", "Pause", "Eine Minute Pause."),
        cue(FRIDAY, 18, 8, "training_fri_pushup_set_3", "Liegestützbrett Satz 3", "Liegestützbrett Nummer neun, grün, Satz 3."),
        cue(FRIDAY, 18, 9, "training_fri_pushup_pause_3", "Pause", "Eine Minute Pause."),
        cue(FRIDAY, 18, 10, "training_fri_pushup_set_4", "Liegestützbrett Satz 4", "Liegestützbrett Nummer zehn, grün, Satz 4."),
        cue(FRIDAY, 18, 11, "training_fri_transition_pushup_to_row", "Wechsel zu Rudern", "Wechsel zu Rudern. Zwei Minuten."),
        cue(FRIDAY, 18, 13, "training_fri_row_set_1", "Rudern Satz 1", "Rudern schulterbreit im Obergriff, Satz 1."),
        cue(FRIDAY, 18, 14, "training_fri_row_pause_1", "Pause", "Eine Minute Pause."),
        cue(FRIDAY, 18, 15, "training_fri_row_set_2", "Rudern Satz 2", "Rudern eng im Untergriff, Satz 2."),
        cue(FRIDAY, 18, 16, "training_fri_row_pause_2", "Pause", "Eine Minute Pause."),
        cue(FRIDAY, 18, 17, "training_fri_row_set_3", "Rudern Satz 3", "Rudern breit im Obergriff, Satz 3."),
        cue(FRIDAY, 18, 18, "training_fri_transition_row_to_hkr", "Wechsel zu Hanging Knee Raises", "Wechsel zu Hanging Knee Raises. Zwei Minuten."),
        cue(FRIDAY, 18, 20, "training_fri_hkr_set_1", "Hanging Knee Raises Satz 1", "Hanging Knee Raises, Satz 1."),
        cue(FRIDAY, 18, 21, "training_fri_hkr_pause_1", "Pause", "Eine Minute Pause."),
        cue(FRIDAY, 18, 22, "training_fri_hkr_set_2", "Hanging Knee Raises Satz 2", "Hanging Knee Raises, Satz 2."),
        cue(FRIDAY, 18, 23, "training_fri_hkr_pause_2", "Pause", "Eine Minute Pause."),
        cue(FRIDAY, 18, 24, "training_fri_hkr_set_3", "Hanging Knee Raises Satz 3", "Hanging Knee Raises, Satz 3."),
        cue(FRIDAY, 18, 25, "training_fri_transition_hkr_to_plank", "Wechsel zu Plank", "Wechsel zu Plank. Zwei Minuten."),
        cue(FRIDAY, 18, 27, "training_fri_plank_set_1", "Plank Satz 1", "Plank, Satz 1."),
        cue(FRIDAY, 18, 28, "training_fri_plank_pause_1", "Pause", "Eine Minute Pause."),
        cue(FRIDAY, 18, 29, "training_fri_plank_set_2", "Plank Satz 2", "Plank, Satz 2."),
        cue(FRIDAY, 18, 30, "training_fri_plank_pause_2", "Pause", "Eine Minute Pause."),
        cue(FRIDAY, 18, 31, "training_fri_plank_set_3", "Plank Satz 3", "Plank, Satz 3."),
        cue(FRIDAY, 18, 32, "training_fri_done_shower", "Training beendet – duschen", "Training beendet. Jetzt zehn Minuten duschen."),
        cue(FRIDAY, 18, 42, "training_fri_dry_dress", "Abtrocknen und anziehen", "Dusche beendet. Jetzt abtrocknen und anziehen. Bis 18:47.")
    )

    val saturday: List<RoutineEvent> = listOf(
        cue(SATURDAY, 17, 30, "training_sat_pullup_set_1", "Klimmzüge Satz 1", "Training startet. Klimmzüge mit Handtuch im Neutralgriff, Satz 1."),
        cue(SATURDAY, 17, 31, "training_sat_pullup_pause_1", "Pause", "Eine Minute Pause."),
        cue(SATURDAY, 17, 32, "training_sat_pullup_set_2", "Klimmzüge Satz 2", "Klimmzüge schulterbreit im Obergriff, Satz 2."),
        cue(SATURDAY, 17, 33, "training_sat_pullup_pause_2", "Pause", "Eine Minute Pause."),
        cue(SATURDAY, 17, 34, "training_sat_pullup_set_3", "Klimmzüge Satz 3", "Klimmzüge schulterbreit im Untergriff, Satz 3."),
        cue(SATURDAY, 17, 35, "training_sat_pullup_pause_3", "Pause", "Eine Minute Pause."),
        cue(SATURDAY, 17, 36, "training_sat_pullup_set_4", "Klimmzüge Satz 4", "Klimmzüge breit im Obergriff, Satz 4."),
        cue(SATURDAY, 17, 37, "training_sat_transition_pullup_to_lat", "Wechsel zu Latzug", "Wechsel zu Latzug. Zwei Minuten."),
        cue(SATURDAY, 17, 39, "training_sat_lat_set_1", "Latzug Satz 1", "Latzug schulterbreit im Obergriff, Satz 1."),
        cue(SATURDAY, 17, 40, "training_sat_lat_pause_1", "Pause", "Eine Minute Pause."),
        cue(SATURDAY, 17, 41, "training_sat_lat_set_2", "Latzug Satz 2", "Latzug eng im Untergriff, Satz 2."),
        cue(SATURDAY, 17, 42, "training_sat_lat_pause_2", "Pause", "Eine Minute Pause."),
        cue(SATURDAY, 17, 43, "training_sat_lat_set_3", "Latzug Satz 3", "Latzug breit im Obergriff, Satz 3."),
        cue(SATURDAY, 17, 44, "training_sat_transition_lat_to_dips", "Wechsel zu Dips", "Wechsel zu Dips. Zwei Minuten."),
        cue(SATURDAY, 17, 46, "training_sat_dips_set_1", "Dips Satz 1", "Dips aufrecht für Trizeps, Satz 1."),
        cue(SATURDAY, 17, 47, "training_sat_dips_pause_1", "Pause", "Eine Minute Pause."),
        cue(SATURDAY, 17, 48, "training_sat_dips_set_2", "Dips Satz 2", "Dips leicht vorgebeugt, Satz 2."),
        cue(SATURDAY, 17, 49, "training_sat_dips_pause_2", "Pause", "Eine Minute Pause."),
        cue(SATURDAY, 17, 50, "training_sat_dips_set_3", "Dips Satz 3", "Dips aufrecht für Trizeps, Satz 3."),
        cue(SATURDAY, 17, 51, "training_sat_dips_pause_3", "Pause", "Eine Minute Pause."),
        cue(SATURDAY, 17, 52, "training_sat_dips_set_4", "Dips Satz 4", "Dips leicht vorgebeugt, Satz 4."),
        cue(SATURDAY, 17, 53, "training_sat_transition_dips_to_butterfly", "Wechsel zu Butterfly", "Wechsel zu Butterfly. Zwei Minuten."),
        cue(SATURDAY, 17, 55, "training_sat_butterfly_set_1", "Butterfly Satz 1", "Butterfly, Satz 1."),
        cue(SATURDAY, 17, 56, "training_sat_butterfly_pause_1", "Pause", "Eine Minute Pause."),
        cue(SATURDAY, 17, 57, "training_sat_butterfly_set_2", "Butterfly Satz 2", "Butterfly, Satz 2."),
        cue(SATURDAY, 17, 58, "training_sat_butterfly_pause_2", "Pause", "Eine Minute Pause."),
        cue(SATURDAY, 17, 59, "training_sat_butterfly_set_3", "Butterfly Satz 3", "Butterfly, Satz 3."),
        cue(SATURDAY, 18, 0, "training_sat_transition_butterfly_to_pushup", "Wechsel zu Liegestützbrett", "Wechsel zu Liegestützbrett. Zwei Minuten."),
        cue(SATURDAY, 18, 2, "training_sat_pushup_set_1", "Liegestützbrett Satz 1", "Liegestützbrett Nummer eins, blau, Satz 1."),
        cue(SATURDAY, 18, 3, "training_sat_pushup_pause_1", "Pause", "Eine Minute Pause."),
        cue(SATURDAY, 18, 4, "training_sat_pushup_set_2", "Liegestützbrett Satz 2", "Liegestützbrett Nummer vier, rot, Satz 2."),
        cue(SATURDAY, 18, 5, "training_sat_pushup_pause_2", "Pause", "Eine Minute Pause."),
        cue(SATURDAY, 18, 6, "training_sat_pushup_set_3", "Liegestützbrett Satz 3", "Liegestützbrett Nummer sieben, gelb, Satz 3."),
        cue(SATURDAY, 18, 7, "training_sat_pushup_pause_3", "Pause", "Eine Minute Pause."),
        cue(SATURDAY, 18, 8, "training_sat_pushup_set_4", "Liegestützbrett Satz 4", "Liegestützbrett Nummer zehn, grün, Satz 4."),
        cue(SATURDAY, 18, 9, "training_sat_transition_pushup_to_squat", "Wechsel zu Kniebeugen", "Wechsel zu Kniebeugen. Zwei Minuten."),
        cue(SATURDAY, 18, 11, "training_sat_squat_set_1", "Kniebeugen Satz 1", "Kniebeugen, Satz 1."),
        cue(SATURDAY, 18, 12, "training_sat_squat_pause_1", "Pause", "Eine Minute Pause."),
        cue(SATURDAY, 18, 13, "training_sat_squat_set_2", "Kniebeugen Satz 2", "Kniebeugen, Satz 2."),
        cue(SATURDAY, 18, 14, "training_sat_squat_pause_2", "Pause", "Eine Minute Pause."),
        cue(SATURDAY, 18, 15, "training_sat_squat_set_3", "Kniebeugen Satz 3", "Kniebeugen, Satz 3."),
        cue(SATURDAY, 18, 16, "training_sat_squat_pause_3", "Pause", "Eine Minute Pause."),
        cue(SATURDAY, 18, 17, "training_sat_squat_set_4", "Kniebeugen Satz 4", "Kniebeugen, Satz 4."),
        cue(SATURDAY, 18, 18, "training_sat_transition_squat_to_lunges", "Wechsel zu Ausfallschritte", "Wechsel zu Ausfallschritte. Zwei Minuten."),
        cue(SATURDAY, 18, 20, "training_sat_lunges_set_1", "Ausfallschritte Satz 1", "Ausfallschritte, Satz 1."),
        cue(SATURDAY, 18, 21, "training_sat_lunges_pause_1", "Pause", "Eine Minute Pause."),
        cue(SATURDAY, 18, 22, "training_sat_lunges_set_2", "Ausfallschritte Satz 2", "Ausfallschritte, Satz 2."),
        cue(SATURDAY, 18, 23, "training_sat_lunges_pause_2", "Pause", "Eine Minute Pause."),
        cue(SATURDAY, 18, 24, "training_sat_lunges_set_3", "Ausfallschritte Satz 3", "Ausfallschritte, Satz 3."),
        cue(SATURDAY, 18, 25, "training_sat_transition_lunges_to_leg_extension", "Wechsel zu Beinstrecker", "Wechsel zu Beinstrecker. Zwei Minuten."),
        cue(SATURDAY, 18, 27, "training_sat_leg_extension_set_1", "Beinstrecker Satz 1", "Beinstrecker, Satz 1."),
        cue(SATURDAY, 18, 28, "training_sat_leg_extension_pause_1", "Pause", "Eine Minute Pause."),
        cue(SATURDAY, 18, 29, "training_sat_leg_extension_set_2", "Beinstrecker Satz 2", "Beinstrecker, Satz 2."),
        cue(SATURDAY, 18, 30, "training_sat_leg_extension_pause_2", "Pause", "Eine Minute Pause."),
        cue(SATURDAY, 18, 31, "training_sat_leg_extension_set_3", "Beinstrecker Satz 3", "Beinstrecker, Satz 3."),
        cue(SATURDAY, 18, 32, "training_sat_transition_leg_extension_to_hkr", "Wechsel zu Hanging Knee Raises", "Wechsel zu Hanging Knee Raises. Zwei Minuten."),
        cue(SATURDAY, 18, 34, "training_sat_hkr_set_1", "Hanging Knee Raises Satz 1", "Hanging Knee Raises, Satz 1."),
        cue(SATURDAY, 18, 35, "training_sat_hkr_pause_1", "Pause", "Eine Minute Pause."),
        cue(SATURDAY, 18, 36, "training_sat_hkr_set_2", "Hanging Knee Raises Satz 2", "Hanging Knee Raises, Satz 2."),
        cue(SATURDAY, 18, 37, "training_sat_hkr_pause_2", "Pause", "Eine Minute Pause."),
        cue(SATURDAY, 18, 38, "training_sat_hkr_set_3", "Hanging Knee Raises Satz 3", "Hanging Knee Raises, Satz 3."),
        cue(SATURDAY, 18, 39, "training_sat_transition_hkr_to_plank", "Wechsel zu Plank", "Wechsel zu Plank. Zwei Minuten."),
        cue(SATURDAY, 18, 41, "training_sat_plank_set_1", "Plank Satz 1", "Plank, Satz 1."),
        cue(SATURDAY, 18, 42, "training_sat_plank_pause_1", "Pause", "Eine Minute Pause."),
        cue(SATURDAY, 18, 43, "training_sat_plank_set_2", "Plank Satz 2", "Plank, Satz 2."),
        cue(SATURDAY, 18, 44, "training_sat_plank_pause_2", "Pause", "Eine Minute Pause."),
        cue(SATURDAY, 18, 45, "training_sat_plank_set_3", "Plank Satz 3", "Plank, Satz 3."),
        cue(SATURDAY, 18, 46, "training_sat_done_shower", "Training beendet – duschen", "Training beendet. Jetzt zehn Minuten duschen."),
        cue(SATURDAY, 18, 56, "training_sat_dry_dress", "Abtrocknen und anziehen", "Dusche beendet. Jetzt abtrocknen und anziehen. Bis 19:01.")
    )

    val allEvents: List<RoutineEvent> =
        monday + tuesday + wednesday + thursday + friday + saturday
}
